module.exports = {
  dataCategory: [
    {
      id: 0,
      category_name: "house",
      description: "This Property is close to the House.",
      category_title: "House",
      category_img: "house-svgrepo-com.svg",
    },
    {
      id: 1,
      category_name: "apartment",
      description: "This is a Property which is Apartment.",
      category_title: "Apartment",
      category_img: "apartment-left-svgrepo-com.svg",
    },
    {
      id: 2,
      category_name: "barn",
      description: "This is a Property is close to the Barn",
      category_title: "Barn",
      category_img: "barn-svgrepo-com.svg",
    },
    {
      id: 3,
      category_name: "bed & breakfast",
      description: "This Property is considerd a Earth Bed & breakfast",
      category_title: "Bed & breakfast",
      category_img: "bed-breakfast-svgrepo-com.svg",
    },
    {
      id: 4,
      category_name: "boat",
      description: "This Property is Boat",
      category_title: "Boat",
      category_img: "boat-svgrepo-com.svg",
    },
    {
      id: 5,
      category_name: "cabin",
      description: "This property has an amazing Cabin",
      category_title: "Cabin",
      category_img: "cabin-svgrepo-com.svg",
    },
    {
      id: 6,
      category_name: "camper/RV",
      description: "This property puts a big focus on Camper/RV ",
      category_title: "Camper/RV",
      category_img: "campervan-svgrepo-com.svg",
    },
    {
      id: 7,
      category_name: "casa particular",
      description: "This property has an amazing Casa particular",
      category_title: "Casa particular",
      category_img: "casa-particular-svgrepo-com.svg",
    },
    {
      id: 8,
      category_name: "castle",
      description: "This property is considered a tiny Castle ",
      category_title: "Castle",
      category_img: "castle-svgrepo-com.svg",
    },
    {
      id: 9,
      category_name: "cave",
      description: "This Property is considered Cave",
      category_title: "Cave",
      category_img: "cave-svgrepo-com.svg",
    },
    {
      id: 10,
      category_name: "container ",
      description: "This Property is located on the Container ",
      category_title: "Container ",
      category_img: "container-svgrepo-com.svg",
    },
    {
      id: 11,
      category_name: "cycladic home",
      description: "This Property has a Cycladic home",
      category_title: "Cycladic home",
      category_img: "cycladic-home-svgrepo-com.svg",
    },
    {
      id: 12,
      category_name: "dammuso",
      description: "This Property is located near to a Dammuso",
      category_title: "Dammuso",
      category_img: "dammuso-svgrepo-com.svg",
    },
    {
      id: 13,
      category_name: "dome",
      description: "This Property is located near to a Dome",
      category_title: "Dome",
      category_img: "dome-svgrepo-com.svg",
    },
    {
      id: 14,
      category_name: "guesthouse",
      description: "This Property is located near to a Guest House",
      category_title: "Guesthouse",
      category_img: "guest-house-svgrepo-com.svg",
    },
    {
      id: 16,
      category_name: "houseboat",
      description: "This Property is located near to a Guest Hotel",
      category_title: "Houseboat",
      category_img: "houseboat-svgrepo-com.svg",
    },
    {
      id: 17,
      category_name: "kezhan",
      description: "This Property is located near to a Guest Kezhan",
      category_title: "Kezhan",
      category_img: "kezhan-svgrepo-com.svg",
    },
    {
      id: 18,
      category_name: "ryokan ",
      description: "This Property is located near to a Guest Ryokan",
      category_title: "Ryokan",
      category_img: "ryokan-svgrepo-com.svg",
    },
    {
      id: 19,
      category_name: "tent",
      description: "This Property is located near to a Tent ",
      category_title: "Tent",
      category_img: "tent-svgrepo-com.svg",
    },
    {
      id: 20,
      category_name: "tiny home",
      description: "This Property is located near to a tiny home ",
      category_title: "Tiny home",
      category_img: "tiny-home-svgrepo-com.svg",
    },
    {
      id: 21,
      category_name: "tower",
      description: "This Property is located near to a tower ",
      category_title: "Tower",
      category_img: "tower-svgrepo-com.svg",
    },
    {
      id: 22,
      category_name: "tree-house",
      description: "This Property is located near to a tower ",
      category_title: "Treehouse",
      category_img: "tree-house-svgrepo-com.svg",
    },
    {
      id: 23,
      category_name: "trullo",
      description: "This Property is located near to a tower ",
      category_title: "Trullo",
      category_img: "trullo-svgrepo-com.svg",
    },
    {
      id: 24,
      category_name: "windmill",
      description: "This Property is located near to a tower ",
      category_title: "Windmill",
      category_img: "windmill-svgrepo-com.svg",
    },
    {
      id: 25,
      category_name: "yurt",
      description: "This Property is located near to a tower ",
      category_title: "Yurt",
      category_img: "yurt-svgrepo-com.svg",
    },
  ],
  dataPlace: [
    {
      type_name: "entire",
      type_img: "entire.jpg",
      type_title: "An entire place",
      type_desc: "Guests have the whole place to themselves.",
    },
    {
      type_name: "room",
      type_img: "room.jpg",
      type_title: "A room",
      type_desc:
        "Guests have their own room in a home, plus access to shared spaces.",
    },
    {
      type_name: "shared",
      type_img: "shared.png",
      type_title: "A shared room",
      type_desc:
        "Guests sleep in a room or common area that may be shared with you or others.",
    },
  ],
  dataAmenity: [
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "Wifi",
      img_name: "wifi-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "TV",
      img_name: "tv-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "Kitchen",
      img_name: "kitchen-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "Washer",
      img_name: "washing-machine-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "Free parking on premises",
      img_name: "parking-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "Paid parking on premises",
      img_name: "paid-parking-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "Air conditioning",
      img_name: "air-conditioning-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "1be9f648-95fb-4c3a-8782-a8ba43e88cb8",
      name: "Dedicated workspace",
      img_name: "workspace-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Pool",
      img_name: "pool-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Hot tub",
      img_name: "hot-tub-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Patio",
      img_name: "patio-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "BBQ grill",
      img_name: "bbq-grill-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Outdoor dining area",
      img_name: "outdoor-dining-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Fire pit",
      img_name:
        "bonfire-campfire-fire-fireplace-firewood-wood-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Pool table",
      img_name: "pool-table-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Indoor fireplace",
      img_name: "fireplace-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Piano",
      img_name: "piano-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Exercise equipment",
      img_name: "gym-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Lake access",
      img_name: "lake-area-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Beach access",
      img_name: "beach-area-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Ski-in/Ski-out",
      img_name: "ski-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "9fa7fbf5-d8de-4758-be97-5f120d10fd1a",
      name: "Outdoor shower",
      img_name: "shower-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "020b81c7-7f44-4842-8c11-c61a83267b0c",
      name: "Smoke alarm",
      img_name: "smoke-alarm-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "020b81c7-7f44-4842-8c11-c61a83267b0c",
      name: "First aid kit",
      img_name: "first-aid-kit-svgrepo-com" + ".svg",
    },
    {
      amenity_type_id: "020b81c7-7f44-4842-8c11-c61a83267b0c",
      name: "Fire extinguisher",
      img_name: "fire-extinguisher-svgrepo-com" + ".svg",
    },
  ],
  dataDiscountTypes: [
    {
      type_name: "first 3 bookings",
      title: "New listing promotion",
      desc: "Offer 20% off your first 3 bookings",
      order: 1,
      edit: false,
    },
    {
      type_name: "7nights",
      title: "Weekly discount",
      desc: "For stays of 7 nights or more",
      order: 2,
      edit: true,
    },
    {
      type_name: "28nights",
      title: "Monthly discount",
      desc: "For stays of 28 nights or more",
      order: 3,
      edit: true,
    },
  ],
};
